"use node";

import { action } from "../_generated/server";
import { api } from "../_generated/api";
import { v } from "convex/values";

import { getAllManagedEntries } from "../lib/contentstack/retrieve.js";
import { createEntry, updateEntry, publishEntry, deleteEntry } from "../lib/contentstack/update.js";
import { config } from "../lib/config.js";
import { getAllSphereContents } from "../lib/sphere/retrieve.js";
import { mapSphereToBlogPost } from "../lib/sphere/blogPostMapper.js";
import { localeValidator } from "../lib/locales";
import allSportIdsData from "../lib/fedid/all_sport_ids.json" with { type: "json" };
import { contentTypeValidator } from "../lib/contentstack/types";

/**
 * Fetch all published Sphere articles for the configured sport IDs, then
 * create or update matching `blog_post` entries in ContentStack and publish them.
 *
 * - Uses `all_sport_ids.json` as the dd_sports filter (generated by `generate:sport-mapping`).
 * - Matches Sphere ↔ CS via the `sphere_id` field.
 * - Updates are triggered when `sphere.updated_at > cs.last_sphere_update`.
 * - Set `dryRun: true` to validate the mapping without writing anything.
 *
 * @example
 * await api.operations.sphereImport({
 *   locale: "en-GB",
 *   sphereContentTypeId: "875ef604-5ca2-4ed9-96b7-15e6c6e0fd0d",
 *   csContentTypeUid: "blog_post",
 * })
 */
export const sphereImport = action({
  args: {
    locale: localeValidator,
    /** Sphere content type UUID */
    sphereContentTypeId: v.string(),
    /** ContentStack content type UID */
    csContentTypeUid: contentTypeValidator,
    /** When true, fetch and map entries but skip all CS writes */
    dryRun: v.optional(v.boolean()),
  },

  handler: async (ctx, args) => {
    const { locale, sphereContentTypeId, csContentTypeUid, dryRun = false } = args;
    const allSportIds = allSportIdsData as string[];

    console.log(`\n=== Sphere Import ===`);
    console.log(`  Sphere type : ${sphereContentTypeId}`);
    console.log(`  CS type     : ${csContentTypeUid}`);
    console.log(`  Locale      : ${locale}`);
    console.log(`  Sport IDs   : ${allSportIds.length} sport IDs as filter`);
    console.log(`  Dry run     : ${dryRun}`);

    // 1. Fetch all matching published Sphere entries
    const sphereEntries = await getAllSphereContents({
      contentTypeId: sphereContentTypeId,
      locale,
      status: 1,
      ddSports: allSportIds.map(Number),
    });
    console.log(`  Sphere entries fetched: ${sphereEntries.length}`);

    // 2. Fetch all existing CS entries and index by sphere_id
    const csEntries = await getAllManagedEntries(csContentTypeUid, { locale });
    const csMap = new Map<string, Record<string, unknown>>();
    for (const entry of csEntries) {
      const sphereId = entry["sphere_id"];
      if (typeof sphereId === "string") {
        csMap.set(sphereId, entry as Record<string, unknown>);
      }
    }
    console.log(`  CS entries fetched: ${csEntries.length} (${csMap.size} with sphere_id)`);

    const { environment, branch } = config.contentstack;
    const publishParams = {
      environments: [environment],
      locales: [locale],
    };

    // 3. Process each Sphere entry
    type FailedItem = { sphereId: string; title: string; step: string; error: string };
    const created: string[] = [];
    const updated: string[] = [];
    const skipped: string[] = [];
    const failed: FailedItem[] = [];

    for (const sphereEntry of sphereEntries) {
      const sphereId = sphereEntry.id;
      const title = sphereEntry.title;

      try {
        const mappedData = mapSphereToBlogPost(sphereEntry);
        const csEntry = csMap.get(sphereId);

        if (!csEntry) {
          // Create new entry
          if (dryRun) {
            created.push(sphereId);
            continue;
          }
          const newEntry = await createEntry(csContentTypeUid, mappedData, locale);
          try {
            await publishEntry(csContentTypeUid, newEntry.uid, publishParams, locale);
          } catch (publishErr) {
            // Roll back the orphaned draft to keep CS clean
            try { await deleteEntry(csContentTypeUid, newEntry.uid); } catch { /* best-effort */ }
            throw publishErr;
          }
          created.push(sphereId);
        } else {
          // Check if update needed: date changed OR taxonomies are out of sync
          const sphereUpdatedAt = sphereEntry.updated_at;
          const csLastUpdate = csEntry["last_sphere_update"];
          const sphereDate = typeof sphereUpdatedAt === "string" ? new Date(sphereUpdatedAt) : null;
          const csDate = typeof csLastUpdate === "string" ? new Date(csLastUpdate) : null;
          // Treat an invalid or missing csLastUpdate as "never updated" → always sync
          const dateChanged =
            sphereDate != null &&
            !isNaN(sphereDate.getTime()) &&
            (csDate == null || isNaN(csDate.getTime()) || sphereDate > csDate);

          const csTaxonomies = csEntry["taxonomies"];
          const actualTerms = new Set(
            Array.isArray(csTaxonomies)
              ? (csTaxonomies as Array<{ term_uid: string }>).map((t) => t.term_uid)
              : []
          );
          const expectedTermUids = (mappedData["taxonomies"] as Array<{ term_uid: string }>).map(
            (t) => t.term_uid
          );
          const taxonomiesOutOfSync =
            actualTerms.size !== expectedTermUids.length ||
            expectedTermUids.some((uid) => !actualTerms.has(uid));

          const needsUpdate = dateChanged || taxonomiesOutOfSync;

          if (!needsUpdate) {
            skipped.push(sphereId);
            continue;
          }

          if (dryRun) {
            updated.push(sphereId);
            continue;
          }
          const entryUid = csEntry["uid"] as string;
          await updateEntry(csContentTypeUid, entryUid, { entry: mappedData }, locale);
          await publishEntry(csContentTypeUid, entryUid, publishParams, locale);
          updated.push(sphereId);
        }
      } catch (err) {
        const error = err instanceof Error ? err.message : String(err);
        const step = csMap.has(sphereId) ? "update" : "create";
        failed.push({ sphereId, title, step, error });
        console.error(`  ✗ [${step}] ${title} (${sphereId}): ${error}`);
      }
    }

    const summary = {
      total: sphereEntries.length,
      created: created.length,
      updated: updated.length,
      skipped: skipped.length,
      failed: failed.length,
    };

    console.log(`\n  Results (dryRun=${dryRun}):`);
    console.log(`  ✅ Created : ${summary.created}`);
    console.log(`  🔄 Updated : ${summary.updated}`);
    console.log(`  ⏭  Skipped : ${summary.skipped}`);
    console.log(`  ✗  Failed  : ${summary.failed}`);
    console.log(`  branch=${branch}, env=${environment}`);
    console.log("====================\n");

    await ctx.runMutation(api.services.logs.writelog, {
      type: "sphereImport",
      status: failed.length === 0 ? "success" : "error",
      params: { locale, sphereContentTypeId, csContentTypeUid, dryRun },
      result: { summary },
      error: failed.length > 0 ? `${failed.length} item(s) failed` : undefined,
    });

    return { summary, params: { locale, sphereContentTypeId, csContentTypeUid, dryRun }, failed };
  },
});
